# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.12.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.12.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/forestfinnigan/Documents/OpenFace-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/forestfinnigan/Documents/OpenFace-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.12.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.12.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.12.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.12.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.12.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.12.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.12.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.12.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /Users/forestfinnigan/Documents/OpenFace-master && $(CMAKE_COMMAND) -E cmake_progress_start /Users/forestfinnigan/Documents/OpenFace-master/CMakeFiles /Users/forestfinnigan/Documents/OpenFace-master/exe/GazeClassifier/CMakeFiles/progress.marks
	cd /Users/forestfinnigan/Documents/OpenFace-master && $(MAKE) -f CMakeFiles/Makefile2 exe/GazeClassifier/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/forestfinnigan/Documents/OpenFace-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/forestfinnigan/Documents/OpenFace-master && $(MAKE) -f CMakeFiles/Makefile2 exe/GazeClassifier/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/forestfinnigan/Documents/OpenFace-master && $(MAKE) -f CMakeFiles/Makefile2 exe/GazeClassifier/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/forestfinnigan/Documents/OpenFace-master && $(MAKE) -f CMakeFiles/Makefile2 exe/GazeClassifier/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/forestfinnigan/Documents/OpenFace-master && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
exe/GazeClassifier/CMakeFiles/GazeClassifier.dir/rule:
	cd /Users/forestfinnigan/Documents/OpenFace-master && $(MAKE) -f CMakeFiles/Makefile2 exe/GazeClassifier/CMakeFiles/GazeClassifier.dir/rule
.PHONY : exe/GazeClassifier/CMakeFiles/GazeClassifier.dir/rule

# Convenience name for target.
GazeClassifier: exe/GazeClassifier/CMakeFiles/GazeClassifier.dir/rule

.PHONY : GazeClassifier

# fast build rule for target.
GazeClassifier/fast:
	cd /Users/forestfinnigan/Documents/OpenFace-master && $(MAKE) -f exe/GazeClassifier/CMakeFiles/GazeClassifier.dir/build.make exe/GazeClassifier/CMakeFiles/GazeClassifier.dir/build
.PHONY : GazeClassifier/fast

GazeClassifier.o: GazeClassifier.cpp.o

.PHONY : GazeClassifier.o

# target to build an object file
GazeClassifier.cpp.o:
	cd /Users/forestfinnigan/Documents/OpenFace-master && $(MAKE) -f exe/GazeClassifier/CMakeFiles/GazeClassifier.dir/build.make exe/GazeClassifier/CMakeFiles/GazeClassifier.dir/GazeClassifier.cpp.o
.PHONY : GazeClassifier.cpp.o

GazeClassifier.i: GazeClassifier.cpp.i

.PHONY : GazeClassifier.i

# target to preprocess a source file
GazeClassifier.cpp.i:
	cd /Users/forestfinnigan/Documents/OpenFace-master && $(MAKE) -f exe/GazeClassifier/CMakeFiles/GazeClassifier.dir/build.make exe/GazeClassifier/CMakeFiles/GazeClassifier.dir/GazeClassifier.cpp.i
.PHONY : GazeClassifier.cpp.i

GazeClassifier.s: GazeClassifier.cpp.s

.PHONY : GazeClassifier.s

# target to generate assembly for a file
GazeClassifier.cpp.s:
	cd /Users/forestfinnigan/Documents/OpenFace-master && $(MAKE) -f exe/GazeClassifier/CMakeFiles/GazeClassifier.dir/build.make exe/GazeClassifier/CMakeFiles/GazeClassifier.dir/GazeClassifier.cpp.s
.PHONY : GazeClassifier.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... GazeClassifier"
	@echo "... GazeClassifier.o"
	@echo "... GazeClassifier.i"
	@echo "... GazeClassifier.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/forestfinnigan/Documents/OpenFace-master && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

